version: '3'

services:
    prisma:
        container_name: ${UNAME}_prisma
        build:
            context: .
            args: 
                - UID=${UID}
                - GID=${GID}
                - UNAME=${UNAME}
        tty: true
        ports:
            - ${PRISMA_CLIENT_PORT}:5555
        volumes:
            - ./prisma:/home/${UNAME}/prisma
        links:
            - db
            - db:${DB_HOST}
        environment:
            DB_HOST: ${DB_HOST}
            DB_NAME: ${DB_NAME}
            DB_USER: ${DB_USER}
            DB_PASS: ${DB_PASS}
            DB_PORT: ${DB_PORT}
            DATABASE_URL: postgresql://${DB_USER}:${DB_PASS}@${DB_HOST}:${DB_PORT}/${DB_NAME}
    db:
        container_name: ${UNAME}_db
        image: postgres:13.3-alpine
        ports:
            - ${DB_PORT}:5432
        environment:
            TZ: "Asia/Tokyo"
            POSTGRES_DB: ${DB_NAME}
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASS}
            POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
            POSTGRES_HOST_AUTH_METHOD: trust        